version: "3"
services:
  chat:
    build: .
    command: node_modules/.bin/nodemon index.js
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/chat
      - node_modules:/home/app/chat/node_modules
volumes:
  node_modules: {}
